### PR TITLE
fix: reduce combat skill rust rate if PRED2/3/4 are active

### LINKED ISSUE #7: Predator mutations do nothing to prevent skill rust of combat skills
### Describe the bug

The description of the latter three predator mutations (Apex Predator, Predator, and Hunter) imply that combat skills are "more easily learned and **maintained**." I interpret "maintained" as meaning, they rust slower, assuming the player has skill rust enabled. However, no such relative increase in skill retention is observed.

### Steps To Reproduce

0. enable skill rust
1. mutate apex predator
2. set all skills to a big number
3. wait a few hours
4. observe that the combat skills have rusted at the same rate as all the other skills

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 13 (trixie); Release: 13; Codename: trixie; 
- Game Version: f4661e4 [64-bit]
- Graphics Version: Curses
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    No Rail Stations [No_Rail_Stations],
    Weather Variants [weather_variants],
    Tablet e-book [tablet_ebook],
    Bionic Slots [cbm_slots],
    No Monsters [Only_Wildlife]
]

### Additional context

I tested this with vanilla and INT based skill rust.

### PR DESCRIPTION
**Pull request by chirimoya-pudu**
## Purpose of change (The Why)

Resolves #7

## Describe the solution (The How)

Reduces rust rate of combat skills by 20% if PRED3, PRED3 or PRED4 are active

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -4272,6 +4272,15 @@ void Character::do_skill_rust()
...
+
+        // if the current skill is a combat skill and PRED2/3/4 are active, reduce rust rate by 20%
+        if( aSkill.is_combat_skill() &&
+            ( has_trait_flag( trait_flag_PRED2 ) ||
+              has_trait_flag( trait_flag_PRED3 ) ||
+              has_trait_flag( trait_flag_PRED4 ) ) ) {
+            rust_rate_tmp = rust_rate_tmp * 0.8;
+        }
+
         if( skill_level_obj.rust( charged_bio_mem, rust_rate_tmp ) ) {
```
Comment (scarf005) [inline src/character.cpp]: changing `rust_rate_tmp` will create side effect of skill rust rate getting reduced per combat skill encountered, e.g if rust_rate_tmp is 1 and there's combat skill a, b, c, 

a: 0.8 ^ 1
b: 0.8 ^ 2
c: 0.8 ^ 3

which would be inconsistent. it should rather be something like (this shouldn't be commited verbatim):

```suggestion
        // if the current skill is a combat skill and PRED2/3/4 are active, reduce rust rate by 20%
        const auto pred_rate_multiplier = aSkill.is_combat_skill()
        	? has_trait_flag( trait_flag_PRED2 ) ? 0.8
        	: has_trait_flag( trait_flag_PRED3 ) ? 0.6
        	: has_trait_flag( trait_flag_PRED3 ) ? 0.4
        	: 1.0;

        if( skill_level_obj.rust( charged_bio_mem, rust_rate_tmp * pred_rate_multiplier ) ) {
```
so `rust_rate_tmp` stays the same per loop. also, L4252-L4254 suggests less chance to forget per higher predator level, so adjusted for that too.

**Review by scarf005 — CHANGES_REQUESTED** [review]
thanks for the PR, but changing the variable to mutable may cause subtle bugs, so could you check those?

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

File: src/character.cpp (hunk 1 above)
Comment (chirimoya-pudu) [reply src/character.cpp]: I've reworked this section in [26074d8](https://github.com/swe-productivity/Cataclysm-BN/commit/26074d8e20f57e2217eaba2186f322149972b168), I think it does what you suggested.

Comment (chirimoya-pudu) [reply src/character.cpp]: I've reworked this section in [26074d8](https://github.com/swe-productivity/Cataclysm-BN/commit/26074d8e20f57e2217eaba2186f322149972b168) to work as you suggested.

File: src/character.cpp [hunk 2]
```diff
@@ -4272,7 +4272,21 @@ void Character::do_skill_rust()
         const bool charged_bio_mem = get_power_level() > bio_memory->power_trigger &&
                                      has_active_bionic( bio_memory );
         const int oldSkillLevel = skill_level_obj.level();
-        if( skill_level_obj.rust( charged_bio_mem, rust_rate_tmp ) ) {
+
+        // default multiplier is 1; if PRED2/3/4 are enabled, reduce the multiplier accordingly
+        int rust_rate_multiplier = 1;
```
Comment (scarf005) [inline src/character.cpp]:
```suggestion
        float rust_rate_multiplier = 1;
```
int cannot store decimal values, needs to use float here.

**Review by scarf005 — APPROVED** [review]
1. have set all skill level to 5
2. waited for 3 hours
3. lost 1 skill level1. have set all skill level to 5
4. gave apex predator trait
5. skill level loses are much slower
